### ISSUE TITLE
ScrollingContainer can't add Container

### ISSUE THREAD

**Issue by royibernthal** [pixijs/pixi-ui#11]
I'm trying to execute this simple code:

```
var scrollingContainer = new PIXI.UI.ScrollingContainer({ scrollY: true, width: 100, height: 200 });

this.scrollingContainer.addChild(new PIXI.Container());
```

The last line throws an error:

> Container.js:70 Uncaught TypeError: Cannot read property 'parent' of undefined
>     at Container.addChild (Container.js:70)
>     at ScrollingContainer.UIBase.addChild (UIBase.js:321)
>     at ScrollingContainer.addChild (ScrollingContainer.js:103)

If I try to add a sprite instead of a container, everything works as expected - no errors are thrown.

**Comment by ivanpopelyshev** [comment]
There's innerContainer:

https://github.com/pixijs/pixi-ui/blob/master/src/ScrollingContainer.js#L30

**Comment by royibernthal** [comment]
Got it, thanks.

Are there by any chance docs for pixi-ui anywhere? I know it's still WIP but it'd still be very helpful.
