### ISSUE TITLE
[REQUEST] More layouts and  calc-property

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-ui#13]
calc-property  like this : 

```subComp.width = "100% - 20"```

means the width is `parent's width - 20px`

**Comment by bQvle** [comment]
Hi sorry I dont spend much time in here :)

I've thought about this feature and it should be possible, but I've come to the conclusion that its what anchors does. maybe you can come up with an example where anchor wouldn't solve this?

Example of 100% - 20 with anchors
1. subComp.anchorLeft = subComp.anchorRight = 10;
you can split the 20px as you like

let me know what you think

**Comment by SukantPal** [comment]
After the refactor, you can do this using an anchor layout:

```js
parent.useLayout(new PUXI.AnchorLayout());

parent.addChild(child.setLayoutOptions(new PUXI.AnchorLayoutOptions(
   20, // anchor left
   0,
   1,
   1);
```
