### ISSUE TITLE
How to make typescript difinition?

### ISSUE THREAD

**Issue by sergiy-oliynik** [pixijs/pixi-ui#16]
Hi, bQvle. First of all thanks for good library. Currently i'm developing easy game with pixi-typescript and i would like to make ui with your tool. Can i generate typescript definition of your library? Thanks.

**Comment by bQvle** [comment]
Hi Sergiy,

I dont know if it can be done easy, I dont believe the docs is good enough to auto generate it. however @ivanpopelyshev is planning porting pixi-ui to typescript. When that's done further development will be in the typescript branch.

**Comment by ivanpopelyshev** [comment]
Yep, I have to defeat my laziness.

**Comment by apptaro** [comment]
@bQvle @ivanpopelyshev any updates on typescript version?

**Comment by ivanpopelyshev** [comment]
@apptaro we are working on official support of plugins for v5, though we dont have special column yet: https://github.com/pixijs/pixi.js/projects/6 , and all v5 plugins will have typings.

**Comment by englercj** [comment]
You can try this: https://github.com/englercj/tsd-jsdoc

If you encounter any incorrect typings, please report it :)

**Comment by apptaro** [comment]
I figured that even though I can use tsd-jsdoc, most of the jsdoc comment is not there, so d.ts created is not usable :(

**Comment by sbfkcel** [comment]
@apptaro I also feel very necessary

**Comment by Teoxoy** [comment]
@ivanpopelyshev I would like to offer to port the repo to typescript. Would this be welcome or should it be done by a pixi core contributor?

**Comment by ivanpopelyshev** [comment]
Go for it. Another problem is that its old v4 repo and not v5. You can port it to TS first of course, v4 typings are fine.

**Comment by Teoxoy** [comment]
@ivanpopelyshev Since you mentioned a lot of types are missing from pixi v4, what would be better? Updating to pixi v5 first then converting the repo to typescript? Or the other way around?

**Comment by SukantPal** [comment]
Typescript conversion has been complete!
