### ISSUE TITLE
TextInput creation bug

### ISSUE THREAD

**Issue by dearcj** [pixijs/pixi-ui#17]
InputBase.call(this, options.width || (options.background ? options.background.width : 150), options.height || (options.background ? options.background.height : 20), options.tabIndex || 0, options.tabGroup || 0)

I added brackets to ternary operator, otherwise it wont work

Btw it seems like TextInput doesnt work with latest PIXIjs (4.7.0)

**Comment by bQvle** [comment]
this should be fixed aswell :)
