### ISSUE TITLE
Not working with pixi 4.7.0

### ISSUE THREAD

**Issue by dearcj** [pixijs/pixi-ui#18]
I'm using pixiui with pixijs 4.7.0
And text input do not intercept events (focus and keydown)

**Comment by ivanpopelyshev** [comment]
If it has about hitArea, I think we changed its behaviour in 4.7.0

**Comment by dearcj** [comment]
https://codepen.io/dorogoi/pen/xYMBBX/

here's the issue at codepen

**Comment by bQvle** [comment]
The hitArea was never updated because the stage never resized (which is why i haven't encountered this issue) 

It should be fixed now :)
https://codepen.io/bQvle/pen/oEVqEw
