### ISSUE TITLE
TextInput isn't clickable from PIXI.UI.Container

### ISSUE THREAD

**Issue by dearcj** [pixijs/pixi-ui#19]
I previously use PIXI.UI.Container for some offeset stuff, and now PIXI.UI.TextInput isn't clickable at all from container

here is example
https://codepen.io/dorogoi/pen/yvwRav

**Comment by bQvle** [comment]
There have been some interaction changes in pixi, however this should not be an issue if you make sure your container has a size. and the objects is within the containers dimensions.

Ill make a fix when I get the time. unfortunately im quiet busy atm.
