### ISSUE TITLE
Is it "usable" now?

### ISSUE THREAD

**Issue by NoxWings** [pixijs/pixi-ui#2]
I just wanted to know if this project is at a usable state right now or if it is supposed to work at all. 

I have just tried to test the ScrollingContainer with some texts on it and it is giving me some errors saying "updateTransform" is not a function.

On the other hand, what PIXI version am I supposed to use?

Thanks.

**Comment by ivanpopelyshev** [comment]
It is used in "tankwars.io", but no docs yet. If you paste your code or make a fiddle, @bQvle will help you :)

**Comment by NoxWings** [comment]
I've figured I had to create a Stage object and then get everything inside it (because the other components do not extend from PIXI itself).

That is raising some questions. I've got custom components that extend from PIXI.Container and other objects inside PIXI that I'd like to use inside the ScrollingContainer. Is is possible?
From what I've seen I think I can only use PIXI.UI own components inside it right?

**Comment by bQvle** [comment]
Hi NoxWings

Yes you can use it, however its not versioned probably, and no deprication is made for changes. but there should be a working example of everything in the test folder, so you can check the sources of them, if anything breaks.

Every UIObject has a regular PIXI container you can add stuff to. 

The point of UIObjects is that they get updated when the parent changes. so you can Anchor/Position stuff relative to its parent.
remember all positioning values can be specified in % and px

**This is an example how you could add a regular object to an UIObject**
```
var box = new PIXI.UI.Container("100%", 40);  //100% width of parent, height 40px 
box.container.addChild(your_custom_object);
```

**However for ScrollingContainers, you have to add stuff to innerContainer**
```
var scrollBox = new PIXI.UI.ScrollingContainer({
      scrollY: true,
      width: "100%",
      height: "100%"
});   
scrollBox.innerContainer.addChild(your_custom_object);
```

**If you add stuff to the container at runtime, I think you need to combine it like this**
```
var scrollBox = new PIXI.UI.ScrollingContainer({
      scrollY: true,
      width: "100%",
      height: "100%"
});   

var box = new PIXI.UI.Container("100%", 40);  //Give it a size that fits your custom object
box.container.addChild(your_custom_object);

scrollBox.addChild(box);
```

this last example makes sure the the updates is triggered corretly when adding a child to the scrollingContainer.

Once again, feel free to use it, if you have any problems just reach out.

**Comment by NoxWings** [comment]
Thank you very much. I've got my project working with it now.
