### ISSUE TITLE
Multiline options with Enter

### ISSUE THREAD

**Issue by Metatron92** [pixijs/pixi-ui#20]
Hello.

1. Enter button does not consider multiline options.
`
        if (e.which === 13) {
            insertTextAtCaret('\n');
            e.preventDefault();
            return;
        }
`

2. Can you add event for enter button?
Now i try to add new option

`
    var keyDownEvent = function (e) {
        self.lastKeyDown = e.which;
...
}
`
And using event "change" for catch when enter down.

`
this.chatInput.on("change", function (data) {
            if(this.lastKeyDown === 13){
                chat.prevSend();
            }
})
`

**Comment by bQvle** [comment]
Hey Metatron, sorry for the late reply! I'm very busy atm so I only visit pixi-ui when I need it related to my work.

I've added keyup/keydown events to textInput. you can use e.preventDefault() and make you own handeling.

However when I get some time, I will rewrite TextInput entirely.
