### ISSUE TITLE
Right way to create a textured button (hover, click)

### ISSUE THREAD

**Issue by virtualenv** [pixijs/pixi-ui#22]
Hello,

Thanks for the pixi-ui, just loved!
Could you please tell me how to create a textured button, I couldn't understand how to change the background of the button when the mouse is hovering it or clicking it.

Thank you.

Mauricio.

**Comment by bQvle** [comment]
Hi Maurico, 

Sorry for the late reply.

If you are using a button you could do something like.

button.on("hover", function (over) {
    button.background.sprite.texture = over ? texture1 : texture2;
});

button.on("press", function (pressed) {
    button.background.sprite.texture = pressed ? texture1 : texture2;
});

you could also change tint/alpha or even animate it with tweens, using these 2 events.

**Comment by virtualenv** [comment]
Hey! Thank you so much!

Best regards,

Mauricio.
