### ISSUE TITLE
Is this published to NPM?

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi-ui#24]
I can't find it on NPM...

Maybe it's not published yet? Is it ready to be used?

**Comment by a-barbieri** [comment]
As per [documentation](https://github.com/pixijs/pixi.js#npm-install)

```
npm install pixi.js
```

You can read more on the npmjs.org website --> https://www.npmjs.com/package/pixi.js

**Comment by ivanpopelyshev** [comment]
Some people use this codebase for 2 years already. You can get information by reading issues in this repo, reading source code and contacting the author of plugin.

**Comment by englercj** [comment]
To answer your question: no. It looks like it is not published to npm, however it has been used by a few people for projects in the past.

**Comment by SukantPal** [comment]
This repository is progressing towards publishing at `puxi.js`.
