### ISSUE TITLE
Any example with ellipsis?

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi-ui#26]
I'm trying to use the ellipsis but I don't get it to work. There isn't any documentation around it.

What I'm trying to achieve is something like this:
https://stackoverflow.com/questions/3922739/limit-text-length-to-n-lines-using-css

**Comment by SukantPal** [comment]
Interesting feature, dynamic text is not being maintained as of now. If you want to fix it, you're welcome to do so :)
