### ISSUE TITLE
PUXI.TextWidget doesn't apply color settings.

### ISSUE THREAD

**Issue by A-Ota** [pixijs/pixi-ui#39]
I expect PUXI.TextWidget to be able to set colors with PIXI.TextStyle as well as PIXI.Text.
However, PUXI.TextWidget always appears black.

here is example.
https://jsfiddle.net/powder0326/rkabgtfw/47/

**Comment by SukantPal** [comment]
@A-Ota I'm working on adding styling features for widgets. Thanks for your feedback.

Until I get out another release, you might try setting `tint` on `puxiText`. Although that option will be gone once I add styling to the current set of widgets.

**Comment by SukantPal** [comment]
P.S. The next API would look like:

```ts
textWidget.setTextStyle({
  fontFamily: 'Roboto',
  fontSize: 14
})
```

OR with the styles API:

```ts
import { StyleSheet }  from '@puxi/core';

const styles = StyleSheet.create({
  text: {
     fontFamily: 'Roboto',
     padding: 8,
     paddingLeft: 12,
     gravity: 'center'
  }
});

textWidget.setStyle(styles.text);
```

How is it 😃?

**Comment by A-Ota** [comment]
If there are more features available with the Style API, that's fine.
If not, I prefer the same way as PixiJS.
