### ISSUE TITLE
Can pixi-ui support state and skins as gown library ?

### ISSUE THREAD

**Issue by vinhbt** [pixijs/pixi-ui#4]

**Comment by bQvle** [comment]
Not entirely sure what you mean by that. pixi-ui has no "default" visuals/skins. 

It helps you position ui objects relative to one another and the screen. And helps with interactions. (scrollingContainer, drag/drop, Checkbox, Buttons etc)

If you want skins you could start making one layout using a spritesheet, respect frame names, and just swap the spritesheet.
