### ISSUE TITLE
how to add a reusable list?

### ISSUE THREAD

**Issue by redw** [pixijs/pixi-ui#57]
many games require lists, such as leaderboards, friend lists, etc.

**Comment by ShukantPal** [comment]
You can use `LinearLayout`: https://github.com/pixijs/pixi-ui/blob/master/packages/core/src/layout-manager/LinearLayout.ts

**Comment by redw** [comment]
thank you

> You can use `LinearLayout`: https://github.com/pixijs/pixi-ui/blob/master/packages/core/src/layout-manager/LinearLayout.ts

thank you
